on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        dependencies: [ 'locked' ]

    name: PHP ${{ matrix.php }} on ${{ matrix.operating-system }} with ${{ matrix.dependencies }} dependencies

    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - name: Install PEAR
        run: |
          sudo apt-get --fix-broken install
          sudo apt-get install php-pear
          pear list
          sudo pear channel-update pear
          sudo pear upgrade -f pear
          sudo pear install text_diff
          pear list
          pear config-set umask 0022
          sudo pear config-set umask 0022 system

      - run: php -i 
      - name: Run tests
        run: |
          umask 0022
          sudo pear run-tests --ini=" -d include_path=.:/usr/share/php" -q -d -r ./tests
